# Generated by Django 5.0.6 on 2024-07-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
